name: NextJS Build as Export

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name : Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Verify the Output Folder
        run: ls -l out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to netlify
        run: |
          netlify deploy --dir=out --prod \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
      